- name: Main playbook
  hosts: all
  become: true

  tasks:
    - name: Install pip
      pip:
        name: requests
        state: present
      tags:
        - install_pip

- name: Configure datadog on webservers
  hosts: webservers
  become: true
  tasks:
    - name: Install datadog agent
      import_role:
        name: datadog.datadog
      tags:
        - configure_datadog

- name: Deploy Redmine on webservers
  hosts: webservers
  become: true
  tags:
    - deploy_redmine
