- name: Main playbook
  hosts: all
  become: true

  vars_files:
    - group_vars/webservers/vars.yml

  tasks:
    - name: Install pip
      import_role:
        name: geerlingguy.pip
      tags:
        - install_pip

    - name: Install Docker module for pip
      import_role:
        name: geerlingguy.docker
      tags:
        - install_docker

    - name: Configure DataDog
      include_role:
        name: datadog.datadog
      when: "'webservers' in group_names"
      vars:
        agent_datadog_checks: "{{ datadog_checks }}"
      tags:
        - configure_datadog

    - name: Deploy Redmine
      include_role:
        name: deploy_redmine
      tags:
        - deploy_redmine
