- name: Main playbook
  hosts: all
  become: true

- name: Prepare Python and Install Docker
  hosts: all
  become: true
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - update_cache

    - name: Install pip
      include_role:
        name: geerlingguy.pip
      tags:
        - install_pip

- name: Install Docker on webservers
  hosts: webservers
  become: true
  roles:
    - geerlingguy.docker
  tags:
    - install_docker

- name: Configure datadog on webservers
  hosts: webservers
  become: true
  roles:
    - datadog.datadog
  tags:
    - configure_datadog
  vars:
    datadog_api_key: "{{ vault_vars.datadog_api_key }}"
    app_key: "{{ vault_vars.app_key }}"

- name: Deploy Redmine on webservers
  hosts: webservers
  become: true
  roles:
    - deploy_redmine
  tags:
    - deploy_redmine
