---
- name: Ensure /root/ansible_project directory exists
  file:
    path: /root/ansible_project
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Install docker Python library
  pip:
    name: docker
    state: present
  become: true

- name: Create .env file from template
  template:
    src: deploy_redmine/templates/.env.j2
    dest: /root/ansible_project/.env
    owner: root
    group: root
    mode: 0644
  become: true

- name: Pull Redmine Docker image
  docker_image:
    name: redmine:latest
  become: true

- name: Create Redmine data volume
  docker_volume:
    name: redmine_data
  become: true

- name: Run Redmine container
  docker_container:
    name: redmine
    image: "redmine:{{ redmine_version }}"
    env_file: /root/ansible_project/.env
    volumes:
      - redmine_data:/usr/src/redmine/files
    ports:
      - "{{ redmine_external_port }}:3000"
    restart_policy: always
  become: true
  when: "'webservers' in group_names"
